### PR TITLE
search.sunbiz.org scraper

### PR DESCRIPTION
**Pull request by Felipe-ZC**
Review regex's and code in general.

Ready for review.

* Don't use regex to parse HTML!!! (Fixed)

### CODE REVIEW

**Review by lopezdp — COMMENTED** [review]
Going to run this a few times before giving final approval and merging. Give me a day or two, also want to figure out how to run as serverless microservice on Spectrum. I will get back to you asap.

**Review by lopezdp — CHANGES_REQUESTED** [review]
Im just pushing back the PR so I can complete the review with the new methods to capture the right html elements as discussed. Thank you sir!

**Comment by Felipe-ZC** [comment]
@lopezdp ready for review

**Comment by lopezdp** [comment]
@Felipe-ZC 

### Reviewer Checklist
- [x] Changes have addressed the issue
  * See the image below, it works perfectly as we have been discussing. I have iteration notes I would like to add since we are looking at implementing other states.
- [ ] Appropriate Tests Included
  * Let's create a Unit Test file to get code coverage on this since we will migrate it to its own micro service in the other repository. Take a look at the command line arguments I used in the image attached for some ideas. When no results found response below:
```
{
    "data": [
        "THE CORPORATION COMPANY",
        "L.L.C., INC.",
        "LP, LLC"
    ]
}
```
- [x] Code style & in-line documentation appropriate
Not gonna be that picky. I actually love your comments

- [ ] Commit message standards
run: `git log --oneline --stat --pretty` and check the difference between our commits to get an idea. Just want to it to be easy to run through logs

### Additional Functionality
I see you're only returning the `ACTIVE` matches. I'm thinking we should also be able to get a response if a Search Entry comes back as `INACTIVE` or really !== to `ACTIVE` to be able to inform the user/owner of an `INACTIVE` corporation that he cannot register with our Application due to the status, etc...

Good Job...

screen shot 2019-02-20 at 12 14 44 am

**Pull request merged**
